#!/bin/sh
set -e

# Use the new strongswan.service instead of the legacy strongswan-starter
# systemctl unmask strongswan-starter.service
# systemctl enable strongswan-starter.service
systemctl stop strongswan-starter.service > /dev/null 2>&1 || true
systemctl disable strongswan-starter.service > /dev/null 2>&1  || true

# systemctl unmask strongswan.service || true
# systemctl enable strongswan.service || true

#DEBHELPER#

exit 0
